### PR TITLE
Subdomains

### PR DESCRIPTION
**Pull request by behind-design**
Hi!
First of all, this is an awesome package that already saved my life.

But now I'm working on a project where the endpoints are not based on prefixes but subdomains.

It's because of this and the fact that your package does already every setup necessary, that I wanted it to collaborate somehow, implementing the subdomain feature.

Let me know what do you think. And if it could be possible to merge it.

Thanks again!

### CODE REVIEW

**Comment by Hesto** [comment]
@behind-design Cool stuff :). I'll merge it. Thanks!

**Comment by behind-design** [comment]
I separated them because the `$redirectTo` property is not the same as the controllers which mounts the guard in a "prefix route".

Do you know what I mean?

**Comment by behind-design** [comment]
I've just realized that there are some minor changes in files that didn't get pushed.

Let me take a look at those first.

**Comment by behind-design** [comment]
@Hesto I've added an approach to support the Lucid architecture.

With this I've solved the previous missing changes I said in some files.
I'm creating an other pull request with all of it.

Feel free to close this one if u need to.

**Comment by Hesto** [comment]
So should i merge it, the next one or both? :D Im confused now.

**Pull request merged**
